### ISSUE TITLE
egui version is outdated

### ISSUE THREAD

**Issue by coderedart** [jacobsky/egui-stylist#12]
egui has changed a few things around in 0.16 and will change a few more things like font families in 0.17 . this library doesn't work with egui 0.16 or the present master (0.17 in future) branch. 

any chance that this will get updated to work with those versions?

I really like the style editor btw. feels so clean when editing a style.

**Comment by jacobsky** [comment]
Apologies for the late reply on this. I am actually in the process of working to update this and the underlying theme editor to the latest version.

**Comment by jacobsky** [comment]
@coderedart The latest commit d1035f28f85e688972e85a8aae97ddf7d319333d has been updated to 0.18 for egui. I haven't published the packages as I would like to do some more testing, but it should be in a moderately usable state.

If you encounter any bugs, please feel free to open an issue and I can investigate. One note is that EguiThemes made with previous version will not work anymore. I've had to completely rethink the format to ensure that updating `egui` doesn't cause your themes to crash during deserialization.
